/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lesson.hibernate.view;

/**
 *
 * @author volka
 */
public class MarketFrame extends javax.swing.JFrame {

    /**
     * Creates new form MarketFrame
     */
    public MarketFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_giris = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_YeniUrun = new javax.swing.JButton();
        btn_UrunGuncelle = new javax.swing.JButton();
        btn_StokSorgula = new javax.swing.JButton();
        btn_UrunSatis = new javax.swing.JButton();
        btn_ToplamHasilat = new javax.swing.JButton();
        btn_SatisSorgula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Market Otomasyonu V1.0");

        lbl_giris.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_giris.setText("Hoşgeldiniz..");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        btn_YeniUrun.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_YeniUrun.setText("YENİ ÜRÜN GİRİŞİ");
        btn_YeniUrun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_YeniUrunActionPerformed(evt);
            }
        });

        btn_UrunGuncelle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_UrunGuncelle.setText("ÜRÜN GÜNCELLE");
        btn_UrunGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UrunGuncelleActionPerformed(evt);
            }
        });

        btn_StokSorgula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_StokSorgula.setText("STOK SORGULA");
        btn_StokSorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_StokSorgulaActionPerformed(evt);
            }
        });

        btn_UrunSatis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_UrunSatis.setText("ÜRÜN SATIŞ");
        btn_UrunSatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UrunSatisActionPerformed(evt);
            }
        });

        btn_ToplamHasilat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ToplamHasilat.setText("TOPLAM HASILAT");
        btn_ToplamHasilat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ToplamHasilatActionPerformed(evt);
            }
        });

        btn_SatisSorgula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_SatisSorgula.setText("SATIŞ SORGULA");
        btn_SatisSorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SatisSorgulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_StokSorgula, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_SatisSorgula, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_YeniUrun, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btn_UrunGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_UrunSatis, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(225, 225, 225))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_ToplamHasilat, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btn_UrunSatis, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_YeniUrun, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_UrunGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SatisSorgula, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_StokSorgula, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_ToplamHasilat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(131, 131, 131))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(lbl_giris)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lbl_giris)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void giris(String username){
        lbl_giris.setText("Hoşgeldiniz " + username);
    }
    
    private void btn_YeniUrunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_YeniUrunActionPerformed
        UrunGirisFrame ugf = new UrunGirisFrame();
        ugf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_YeniUrunActionPerformed

    private void btn_StokSorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StokSorgulaActionPerformed
        StokFrame sf = new StokFrame();
        sf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_StokSorgulaActionPerformed

    private void btn_UrunGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UrunGuncelleActionPerformed
        UrunGuncelleFrame guncelleF = new UrunGuncelleFrame();
        guncelleF.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_UrunGuncelleActionPerformed

    private void btn_UrunSatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UrunSatisActionPerformed
        SatisFrame sf = new SatisFrame();
        sf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_UrunSatisActionPerformed

    private void btn_ToplamHasilatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ToplamHasilatActionPerformed
        ToplamHasilatFrame thf = new ToplamHasilatFrame();
        thf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_ToplamHasilatActionPerformed

    private void btn_SatisSorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SatisSorgulaActionPerformed
        SatislarFrame satislarF = new SatislarFrame();
        satislarF.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_SatisSorgulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarketFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SatisSorgula;
    private javax.swing.JButton btn_StokSorgula;
    private javax.swing.JButton btn_ToplamHasilat;
    private javax.swing.JButton btn_UrunGuncelle;
    private javax.swing.JButton btn_UrunSatis;
    private javax.swing.JButton btn_YeniUrun;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_giris;
    // End of variables declaration//GEN-END:variables
}
