/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lesson.hibernate.view;

import com.lesson.hibernate.entity.satis;
import com.lesson.hibernate.entity.sepet;
import com.lesson.hibernate.entity.toplamHasilat;
import com.lesson.hibernate.entity.urunler;
import com.lesson.hibernate.util.HibernateUtil;
import java.time.LocalDateTime;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author volka
 */
public class SatisFrame extends javax.swing.JFrame {

    /**
     * Creates new form SatisFrame
     */
    public SatisFrame() {
        initComponents();
        txt_BarkodNo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cbx_Kategori = new javax.swing.JComboBox<>();
        txt_ToplamFiyat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_UrunAdi = new javax.swing.JTextField();
        txt_BarkodNo = new javax.swing.JTextField();
        btn_Ekle = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txt_KDV = new javax.swing.JTextField();
        txt_Miktar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_Temizle = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Sepet = new javax.swing.JTable();
        txt_BirimFiyati = new javax.swing.JTextField();
        txt_UrunAdedi = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lbl_ToplamUrun = new javax.swing.JLabel();
        btn_SatisYap = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lbl_ToplamTutar = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_Nakit = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        lbl_ParaUstu = new javax.swing.JLabel();
        lbl_kdvTutarı = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_KDVTutari = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel7.setText("Ürün Satış Ekranı");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 305, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 311, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Barkod No :");

        cbx_Kategori.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbx_Kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kuru Gıda", "Şarküteri", "Bakım Ürünleri", "Et ve Et Ürünleri", "Süt ve Süt Ürünleri", "Meyve Sebze", "İçecek", "Temizlik Ürünleri", "Kozmetik ve Kişisel Bakım" }));
        cbx_Kategori.setEnabled(false);

        txt_ToplamFiyat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_ToplamFiyat.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("KDV Oranı :");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Ürün Adı :");

        txt_UrunAdi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_UrunAdi.setEnabled(false);

        txt_BarkodNo.setBackground(new java.awt.Color(255, 102, 0));
        txt_BarkodNo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_BarkodNo.setForeground(new java.awt.Color(255, 255, 255));
        txt_BarkodNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BarkodNoActionPerformed(evt);
            }
        });

        btn_Ekle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Ekle.setText("EKLE");
        btn_Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EkleActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("MİKTAR :");

        txt_KDV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_KDV.setEnabled(false);
        txt_KDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_KDVActionPerformed(evt);
            }
        });

        txt_Miktar.setBackground(new java.awt.Color(255, 102, 0));
        txt_Miktar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_Miktar.setForeground(new java.awt.Color(255, 255, 255));
        txt_Miktar.setText("1");
        txt_Miktar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MiktarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Toplam Fiyat :");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Ürün Kategorisi :");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Ürün Birim Fiyatı :");

        btn_Temizle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Temizle.setText("TEMİZLE");
        btn_Temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TemizleActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Ürün Adedi :");

        table_Sepet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barkod No", "Ürün Adı", "Kategori", "Birim Fiyat", "KDV Tutarı", "Miktar", "Toplam Fiyat"
            }
        ));
        jScrollPane1.setViewportView(table_Sepet);

        txt_BirimFiyati.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_BirimFiyati.setEnabled(false);

        txt_UrunAdedi.setEnabled(false);
        txt_UrunAdedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UrunAdediActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Toplam Ürün :");

        lbl_ToplamUrun.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_ToplamUrun.setForeground(new java.awt.Color(255, 0, 0));
        lbl_ToplamUrun.setText("0 ");

        btn_SatisYap.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_SatisYap.setText("SATIŞ YAP");
        btn_SatisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SatisYapActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel15.setText("NAKİT :");

        lbl_ToplamTutar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_ToplamTutar.setForeground(new java.awt.Color(255, 0, 0));
        lbl_ToplamTutar.setText("0.00 ₺");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel18.setText("TOPLAM TUTAR :");

        txt_Nakit.setBackground(new java.awt.Color(255, 101, 12));
        txt_Nakit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_Nakit.setForeground(new java.awt.Color(255, 255, 255));
        txt_Nakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NakitActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel19.setText("PARA ÜSTÜ :");

        lbl_ParaUstu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_ParaUstu.setForeground(new java.awt.Color(51, 51, 255));
        lbl_ParaUstu.setText("0.00 ₺");

        lbl_kdvTutarı.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_kdvTutarı.setForeground(new java.awt.Color(255, 0, 0));
        lbl_kdvTutarı.setText("0.00 ₺");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Toplam KDV Tutarı :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20))
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ToplamUrun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_kdvTutarı, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(lbl_ToplamTutar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(128, 128, 128)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel15))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ParaUstu, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Nakit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_SatisYap, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_Nakit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(lbl_ParaUstu)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_SatisYap, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ToplamUrun)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(lbl_kdvTutarı))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel18))
                            .addComponent(lbl_ToplamTutar))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        txt_KDVTutari.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_KDVTutari.setEnabled(false);
        txt_KDVTutari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_KDVTutariActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("KDV Tutarı :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_BarkodNo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_UrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel17))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_KDV)
                            .addComponent(txt_BirimFiyati)
                            .addComponent(txt_UrunAdedi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_KDVTutari, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(32, 32, 32))
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ToplamFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_Ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btn_Temizle)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txt_BarkodNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbx_Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_UrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(17, 17, 17))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_UrunAdedi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_BirimFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txt_KDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(txt_KDVTutari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Miktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_ToplamFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_Ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField tf = new JTextField();
    public JTextField tfTutar = new JTextField();

    private void txt_MiktarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MiktarActionPerformed
        try {
            double fiyat = Double.parseDouble(txt_BirimFiyati.getText()) * Double.parseDouble(txt_Miktar.getText());
            txt_ToplamFiyat.setText(String.format(Locale.US, "%.2f", fiyat));
        } catch (Exception e) {
        }
        kdvHesapla();
    }//GEN-LAST:event_txt_MiktarActionPerformed

    private void txt_KDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_KDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_KDVActionPerformed

    private void btn_TemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TemizleActionPerformed
        txt_ToplamFiyat.setText("");
        txt_BarkodNo.setText("");
        txt_KDV.setText("");
        txt_BirimFiyati.setText("");
        txt_Miktar.setText("");
        txt_UrunAdi.setText("");
        txt_UrunAdedi.setText("");
        txt_KDVTutari.setText("");
    }//GEN-LAST:event_btn_TemizleActionPerformed

    void sepetListele() {
        /*geçici olarak kullanılan sepet sınıfındaki verileri her ürün ekleme işleminde 
        table üzerinde gösterebilmek için list metodu kullanıldı.*/
        Session session = HibernateUtil.getSessionFactory().openSession();
        List<sepet> sepets = session.createCriteria(sepet.class).list();
        List<sepet> urun = sepets;
        //sepetteki ürünler list şeklinde alındı ve while döngüsü ile tüm sepete ekli
        //ürünler table nesnesine aktarıldı.
        if (urun.size() > 0) {
            Iterator iter = urun.iterator();
            while (iter.hasNext()) {
                DefaultTableModel model = (DefaultTableModel) table_Sepet.getModel();
                Vector data = new Vector();
                sepet uruns = (sepet) iter.next();
                data.add(uruns.getU_barkodno());
                data.add(uruns.getU_adi());
                data.add(uruns.getU_kategori());
                data.add(uruns.getBirim_fiyat());
                data.add(uruns.getU_kdv());
                data.add(uruns.getMiktar());
                data.add(uruns.getToplam_fiyat());
                model.addRow(data);
            }
        }
    }

    void ClearTable() {
        while (table_Sepet.getRowCount() != 0) {
            ((DefaultTableModel) table_Sepet.getModel()).removeRow(0);
        }
    }

    void hesapla() {
        /*hesapla fonksiyonu ile sepet tablosuna eklenen satılacak olan ürünlerin
        toplam satış tutarları, adetleri ve toplam kdv tutarları table nesnesinden 
        gerekli sütunlardan alınarak for döngüsü ile toplanarak hesaplandı.*/
        double toplamtutar = 0;
        int toplamurun = 0;
        double toplamKDV = 0;
        for (int i = 0; i < table_Sepet.getRowCount(); i++) {
            toplamtutar += Double.parseDouble(table_Sepet.getValueAt(i, 6).toString());
            toplamurun += Integer.parseInt(table_Sepet.getValueAt(i, 5).toString());
            toplamKDV += Double.parseDouble(table_Sepet.getValueAt(i, 4).toString());
        }
        //hesaplanan veriler formatlanarak gerekli component'lere yazıldı.
        lbl_ToplamTutar.setText(String.format(Locale.US, "%.2f", toplamtutar) + " ₺");
        lbl_ToplamUrun.setText(Integer.toString(toplamurun));
        tf.setText(String.format(Locale.US, "%.2f", toplamtutar));
        lbl_kdvTutarı.setText(String.format(Locale.US, "%.2f", toplamKDV) + " ₺");
    }

    void ParaUstuHesapla() {
        //Müşterinin verdiği nakit parayı gerekli kısma girerek para üstünü öğrenmek
        //için fonksiyon yazıldı ve gerekli component'e bilgi yazdırıldı.
        double paraUstu;
        paraUstu = Double.parseDouble(txt_Nakit.getText()) - Double.parseDouble(tf.getText());
        lbl_ParaUstu.setText((String.format(Locale.US, "%.2f", paraUstu)));
    }

    void kdvHesapla() {
        /*Ürünlerin kdv oranına göre kdv tutarını hesaplamak için, ürünün kdv oranı ile
        birim fiyatı üzerinden hesaplama yapıldı. Gerekli format işlemi gerçekleştirildi ve
        kdvTutarı textfield'ına yazdırıldı.*/
        double kdvTutari;
        kdvTutari = (Double.parseDouble(txt_BirimFiyati.getText()) * 
                Integer.parseInt(txt_Miktar.getText()) * Integer.parseInt(txt_KDV.getText())) / 100;
        txt_KDVTutari.setText((String.format(Locale.US, "%.2f", kdvTutari)));
    }

    private void btn_EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EkleActionPerformed
        /*sepet sınıfından yeni nesne oluşturuldu ve gerekli miktar bilgiside girilerek 
        geçici olarak kullanılmak üzere sepet sınıfına kayıt yapıldı.*/
        String selectedItem = cbx_Kategori.getSelectedItem().toString();
        sepet yeniSepet = new sepet(Integer.parseInt(txt_BarkodNo.getText()), selectedItem, txt_UrunAdi.getText(),
                Double.parseDouble(txt_BirimFiyati.getText()), Double.parseDouble(txt_ToplamFiyat.getText()),
                Double.parseDouble(txt_KDVTutari.getText()), Integer.parseInt(txt_Miktar.getText()));
        /*satis sınıfından yeni nesne oluşturuldu ve bilgiler kalıcı olarak saklanmak üzere satış
        sınıfına kaydedildi.*/
        LocalDateTime tarih = LocalDateTime.now();
        satis yeniSatis = new satis(Integer.parseInt(txt_BarkodNo.getText()), selectedItem, txt_UrunAdi.getText(),
                Double.parseDouble(txt_BirimFiyati.getText()), Double.parseDouble(txt_ToplamFiyat.getText()),
                Double.parseDouble(txt_KDVTutari.getText()), Integer.parseInt(txt_Miktar.getText()), tarih);
        //Hibernate save metodu ile gerekli sınıflara kayıt işlemi gerçekleşti.
        Transaction transaction = null;
        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
            transaction = session.beginTransaction();
            session.save(yeniSatis);
            session.save(yeniSepet);

            /*sepete eklenmek üzere barkod no'sundan bilgileri getirilen ürünün
            girilen miktar kadar stok adedinde düşüş işlemi yapıldı.*/
            String hql = "FROM urunler E WHERE E.u_barkodno = " + txt_BarkodNo.getText();
            Query query = session.createQuery(hql);
            List<urunler> result = (List<urunler>) query.list();
            int yeniStok = Integer.parseInt(txt_UrunAdedi.getText()) - Integer.parseInt(txt_Miktar.getText());
            for (urunler u : result) {
                u.setU_miktar(yeniStok);
                //Stok adedi hesaplandıktan sonra update metodu ile sınıf içerisinde güncellendi.
                session.update(u);
            }
            transaction.commit();
            //Sepete yeni ürün eklemek üzere tüm textfield nesneleri temizlendi.
            txt_ToplamFiyat.setText("");
            txt_BarkodNo.setText("");
            txt_KDV.setText("");
            txt_BirimFiyati.setText("");
            txt_Miktar.setText("");
            txt_UrunAdi.setText("");
            txt_UrunAdedi.setText("");
            txt_KDVTutari.setText("");

        } catch (Exception e) {
            if (transaction != null) {
                transaction.rollback();
            }
            e.printStackTrace();
        }
        //fonksiyon olarak yazılan sepeti temizleme, listeleme ve toplam fiyat
        //hesaplama fonksiyonları çağırıldı.
        ClearTable();
        sepetListele();
        hesapla();
        txt_BarkodNo.requestFocus();
    }//GEN-LAST:event_btn_EkleActionPerformed

    /* Hibernate hql ile select sorgusu yazılarak urunler tablosundaki veriler
    ürünün barkod numarasına göre bulunarak gerekli component'lere çekildi. */
    private void txt_BarkodNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BarkodNoActionPerformed
        Transaction transaction = null;
        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
            transaction = session.beginTransaction();
            String hql = "FROM urunler E WHERE E.u_barkodno = " + txt_BarkodNo.getText();
            Query query = session.createQuery(hql);
            List<urunler> result = (List<urunler>) query.list();
            for (urunler u : result) {
                txt_UrunAdi.setText(u.getU_adi());
                cbx_Kategori.setSelectedItem(u.getU_kategori());
                txt_BirimFiyati.setText(String.valueOf(u.getU_satisfiyati()));
                txt_KDV.setText(String.valueOf(u.getU_kdv()));
                txt_UrunAdedi.setText(String.valueOf(u.getU_miktar()));
            }
            txt_Miktar.requestFocus();
            transaction.commit();

        } catch (Exception e) {
            if (transaction != null) {
                transaction.rollback();
            }
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_BarkodNoActionPerformed

    private void btn_SatisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SatisYapActionPerformed

        /*Ürünler sepete eklendikten sonra satış butonuna tıklandıktan sonra hasılat bilgilerini
        saklamak için toplamHasılat sınıfına kasanın toplam tutarı ve o anki saat tarih bilgisi
        kaydedildi.*/
        LocalDateTime hasilattarih = LocalDateTime.now();
        toplamHasilat hasilat = new toplamHasilat(Double.parseDouble(tf.getText()), hasilattarih);
        Transaction transaction = null;
        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
            transaction = session.beginTransaction();
            session.save(hasilat);
            /*Satış butonuna tıklandıktan sonra hesaplamaları yapmak için kullandığımız geçici
            sepet tablosundaki tüm veriler hibernate hql ile delete sorgusu kullanılarak silindi*/
            String hql = "DELETE FROM sepet";
            Query query = session.createQuery(hql);
            int result = query.executeUpdate();
            //Yetkiliye satış ile ilgili bilgi mesajı verildi.
            JOptionPane.showMessageDialog(null, result + " ürün satıldı !", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
            transaction.commit();
            //Gerekli component'ler tekrar satış işlemi için uygun hale getilirilerek temizlendi.
            txt_Nakit.setText("");
            lbl_ParaUstu.setText("0.00 ₺");
            txt_BarkodNo.requestFocus();
        } catch (Exception e) {
            if (transaction != null) {
                transaction.rollback();
            }
            e.printStackTrace();
        }
        /* sepet tablosundaki veriler silindiği için tekrar listeleme ve hesaplama fonksiyonları
        çağırıldı ve satış formu tekrar yeni satış işlemi için hazır hale getirildi. */
        ClearTable();
        sepetListele();
        hesapla();
    }//GEN-LAST:event_btn_SatisYapActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        MarketFrame mf = new MarketFrame();
        mf.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void txt_NakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NakitActionPerformed
        ParaUstuHesapla();
    }//GEN-LAST:event_txt_NakitActionPerformed

    private void txt_KDVTutariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_KDVTutariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_KDVTutariActionPerformed

    private void txt_UrunAdediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UrunAdediActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UrunAdediActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SatisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SatisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SatisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SatisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SatisFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ekle;
    private javax.swing.JButton btn_SatisYap;
    private javax.swing.JButton btn_Temizle;
    private javax.swing.JComboBox<String> cbx_Kategori;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ParaUstu;
    private javax.swing.JLabel lbl_ToplamTutar;
    private javax.swing.JLabel lbl_ToplamUrun;
    private javax.swing.JLabel lbl_kdvTutarı;
    private javax.swing.JTable table_Sepet;
    private javax.swing.JTextField txt_BarkodNo;
    private javax.swing.JTextField txt_BirimFiyati;
    private javax.swing.JTextField txt_KDV;
    private javax.swing.JTextField txt_KDVTutari;
    private javax.swing.JTextField txt_Miktar;
    private javax.swing.JTextField txt_Nakit;
    private javax.swing.JTextField txt_ToplamFiyat;
    private javax.swing.JTextField txt_UrunAdedi;
    private javax.swing.JTextField txt_UrunAdi;
    // End of variables declaration//GEN-END:variables
}
